#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7i820e7r5hc73c5pk90-a.singapore-postgres.render.com/moneymanager_2tr5
spring.datasource.username=moneymanager_2tr5_user
spring.datasource.password=3do9vJ9Cb1nVJnchx0yElawLPQ9nY8by
